# .github/workflows/gh-pages.yml

name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: Killarexe/killarexe.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_ARGS: ''
          CNAME: killarexe.github.io
